### ISSUE TITLE
Can launchbar-livedic support url scheme?

### ISSUE THREAD

**Issue by bolasblack** [nbjahan/launchbar-livedic#4]
Document: https://developer.obdev.at/resources/documentation/launchbar-developer-documentation/#/action-script-types/action-url-script

I really hope it can be supported, then I can use it with PopClip

**Comment by nbjahan** [comment]
@bolasblack I tried, here is the result: needs v1.2.0
`open "x-launchbar:action/nbjahan.launchbar.livedic/lookup?YOUR_QUERY_HERE"`

**Comment by bolasblack** [comment]
@nbjahan Thanks! And you taught me a way to support url scheme with javascript though the main program not written by javascript.
